# Generated by Django 4.0 on 2022-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_likes_alter_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
